# Generated by Django 5.1.15 on 2026-07-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seat',
            name='unique_seat',
        ),
        migrations.AddField(
            model_name='hall',
            name='blocks',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='seat',
            name='block_num',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='rows',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='hall',
            name='seats_per_row',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row_num',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('hall', 'block_num', 'row_num', 'seat_number'), name='unique_seat'),
        ),
    ]
